name: mi_card_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  # If you want to pin Flutter version constraints too, you could add:
  # flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  # iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Recommended lints (configured in analysis_options.yaml)
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
